### PR TITLE
fix: int/float auto-conversion

### LINKED ISSUE #470: [flagd/in-process] float flags with 0.0 value are parsed as ints
The flagd in-process provider _should_ be able to resolve ints as floats, and vice-versa.

To fix:

- modify [this](https://github.com/open-feature/java-sdk-contrib/blob/3190ad2bbc4746eb7efb571af14c73cba7176ea0/providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/resolver/process/InProcessResolver.java#L190) area of the code to support conversion from int/float, float/int
- add relevant tests [here](https://github.com/open-feature/java-sdk-contrib/blob/main/providers/flagd/src/test/java/dev/openfeature/contrib/providers/flagd/resolver/process/InProcessResolverTest.java)
- un-comment float tests [here](https://github.com/open-feature/java-sdk-contrib/blob/main/providers/flagd/src/test/java/dev/openfeature/contrib/providers/flagd/e2e/steps/StepDefinitions.java)

Background:

_Originally posted by @toddbaert in https://github.com/open-feature/java-sdk-contrib/pull/468#discussion_r1342179921_

### PR DESCRIPTION
**Pull request by DBlanchard88**
- Added conversion logic to convert integers to float and floats to integers.
- Created two in process resolver tests to check conversions
- un-commented float/double in Step definitions

Fixes: https://github.com/open-feature/java-sdk-contrib/issues/470

### CODE REVIEW

File: providers/flagd/src/test/java/dev/openfeature/contrib/providers/flagd/e2e/steps/StepDefinitions.java [hunk 1]
```diff
@@ -460,16 +460,15 @@ public void the_resolved_boolean_zero_value_should_be(String expected) {
     // float/double value
     @When("a zero-value float flag with key {string} is evaluated with default value {double}")
     public void a_zero_value_float_flag_with_key_is_evaluated_with_default_value(String flagKey, Double defaultValue) {
-        // TODO: There is a bug here with 0 value floats
-        // this.doubleFlagKey = flagKey;
-        // this.doubleFlagDefaultValue = defaultValue;
+        this.doubleFlagKey = flagKey;
+        this.doubleFlagDefaultValue = defaultValue;
```
Comment (toddbaert) [inline providers/flagd/src/test/java/dev/openfeature/contrib/providers/flagd/e2e/steps/StepDefinitions.java:464]: great to see these work now!

File: providers/flagd/src/test/java/dev/openfeature/contrib/providers/flagd/resolver/process/InProcessResolverTest.java [hunk 2]
```diff
@@ -105,15 +106,53 @@ public void simpleDoubleResolving() throws Exception {
...
+        ProviderEvaluation<Double> providerEvaluation = inProcessResolver.doubleEvaluation("doubleFlag", 0d,
+                new ImmutableContext());
 
         // then
         assertEquals(3.141d, providerEvaluation.getValue());
         assertEquals("one", providerEvaluation.getVariant());
         assertEquals(Reason.STATIC.toString(), providerEvaluation.getReason());
     }
 
+    @Test
```
Comment (toddbaert) [inline providers/flagd/src/test/java/dev/openfeature/contrib/providers/flagd/resolver/process/InProcessResolverTest.java:118]: Tests look right to me.

File: providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/resolver/process/InProcessResolver.java [hunk 3]
```diff
@@ -186,7 +186,14 @@ private <T> ProviderEvaluation<T> resolve(Class<T> type, String key,
...
         }
-
+        // if this is an integer and we are trying to resolve a double, convert
+        if (value instanceof Integer && type == Double.class) {
+            value = ((Integer) value).doubleValue();
+        
+        // if this is a doulbe and we are trying to resolve an integer, convert
+        } else if (value instanceof Double && type == Integer.class) {
+            value = ((Double) value).intValue();
+        }
```
Comment (toddbaert) [inline providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/resolver/process/InProcessResolver.java]: @Kavindu-Dodan I'm not sure I can think of a more elegant way to do this. At first I thought we could just loosen the check on line 197, but since these are boxed types, the cast to `T` at the end isn't enough; we actually have to do a conversion.

**Review by toddbaert — APPROVED** [review]
Thanks for the fix and the testing @DBlanchard88 . Approved, but I will wait to see if @Kavindu-Dodan has a more elegant approach for [this](https://github.com/open-feature/java-sdk-contrib/pull/472#discussion_r1349427677). If not, I will merge.

File: providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/resolver/process/InProcessResolver.java (hunk 3 above)
Comment (Kavindu-Dodan) [reply providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/resolver/process/InProcessResolver.java]: Yes, we need to do a conversion. And the implementation looks good :)

Comment (Kavindu-Dodan) [inline providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/resolver/process/InProcessResolver.java]:
```suggestion
        if (value instanceof Integer && type == Double.class) {
            // if this is an integer and we are trying to resolve a double, convert
            value = ((Integer) value).doubleValue();
        } else if (value instanceof Double && type == Integer.class) {
            // if this is a double and we are trying to resolve an integer, convert
            value = ((Double) value).intValue();
        }
```

suggestion to improve readablity

**Review by Kavindu-Dodan — APPROVED** [review]
LGTM 

@toddbaert  feel free to go ahead with the merge :)

**Comment by toddbaert** [comment]
> LGTM
> 
> @toddbaert feel free to go ahead with the merge :)

Sure I'll wait a bit for @DBlanchard88 to check out your suggestion.
