### PR TITLE
fix: thread memory leak in InProcessResolver

### LINKED ISSUE #1677: Thread memory leak in flagd InProcessResolver
The stateWatcher thread in `InProcessResolver` is not properly closed when the `shutdown()` method is invoked, leading to a memory leak.

Consider implementing a proper shutdown mechanism (similar to that in `FlagStore.shutdown()`).

### PR DESCRIPTION
**Pull request by paul-kraftlauget**
## This PR

- fixes a memory leak in InProcessResolver

### Related Issues

Fixes #1677

### How to test
Please see the unit test in this PR

### CODE REVIEW

File: providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/resolver/process/InProcessResolver.java [hunk 1]
```diff
@@ -69,7 +71,7 @@ public void init() throws Exception {
         flagStore.init();
         final Thread stateWatcher = new Thread(() -> {
             try {
-                while (true) {
+                while (!shutdown.get()) {
```
[the remark this answers is not in the document]
Comment (toddbaert) [reply providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/resolver/process/InProcessResolver.java]: While this is true, what's been added here is an objective improvement.

@paul-kraftlauget ... up to you if you'd like to go further. I do think this comment is correct

**Comment by toddbaert** [comment]
@paul-kraftlauget Thanks a lot! can you fix the DCO failure? You can do a `git commit --amend --signoff` which just gives a legal signoff to the commit.

File: providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/resolver/process/InProcessResolver.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (paul-kraftlauget) [reply providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/resolver/process/InProcessResolver.java]: Yes, it was correct. And looking at the file sync implementation, there wouldn't be another event sent when shutdown, so the leak still would occur. I have pushed an update now. I hope it is ok.

File: providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/resolver/process/InProcessResolver.java [hunk 2]
```diff
@@ -105,12 +109,12 @@ public void init() throws Exception {
...
             } catch (InterruptedException e) {
-                log.warn("Storage state watcher interrupted", e);
-                Thread.currentThread().interrupt();
+                log.debug("Storage state watcher interrupted, most likely shutdown was invoked", e);
             }
-        });
+        }, "InProcessResolver.stateWatcher");
         stateWatcher.setDaemon(true);
         stateWatcher.start();
+        this.stateWatcher.set(stateWatcher);
```
Comment (chrfwow) [inline providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/resolver/process/InProcessResolver.java:78]: I think we should set the reference before starting the thread

File: providers/flagd/src/test/java/dev/openfeature/contrib/providers/flagd/resolver/process/InProcessResolverTest.java [hunk 3]
```diff
@@ -543,6 +544,35 @@ void flagSetMetadataIsOverwrittenByFlagMetadataToEvaluation() throws Exception {
...
+
+        // when
+        inProcessResolver.init();
+        var threadCountAfterInit = currentDaemonThreadCount();
+        inProcessResolver.shutdown();
+
+        // then
+        assertThat(threadCountAfterInit).isGreaterThan(initialThreadCount);
+        Awaitility.await()
+                .untilAsserted(() -> assertThat(currentDaemonThreadCount()).isEqualTo(initialThreadCount));
```
Comment (chrfwow) [inline providers/flagd/src/test/java/dev/openfeature/contrib/providers/flagd/resolver/process/InProcessResolverTest.java]: Could we instead assert that the thread set does not contain a thread named `InProcessResolver.stateWatcher`?

File: providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/resolver/process/InProcessResolver.java (hunk 2 above)
Comment (paul-kraftlauget) [reply providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/resolver/process/InProcessResolver.java:78]: fixed

File: providers/flagd/src/test/java/dev/openfeature/contrib/providers/flagd/resolver/process/InProcessResolverTest.java (hunk 3 above)
Comment (paul-kraftlauget) [reply providers/flagd/src/test/java/dev/openfeature/contrib/providers/flagd/resolver/process/InProcessResolverTest.java]: Added to the test

Comment (paul-kraftlauget) [reply providers/flagd/src/test/java/dev/openfeature/contrib/providers/flagd/resolver/process/InProcessResolverTest.java]: I added it instead of replacing it. I used test-driven development for this, first reproduced the error with a test. It was before I added the thread name. I added the thread name for visibility, not for behavior, although it does make it possiblity for outside code to start interrupting the thread themselves.

I think the daemon thread count check is still valid. In fact, I was debating to start a new thread to first try to let it stop gracefully (and let any final events be sent), then after a given deadline, to forcefully stop it. In any case, the behavior to test is that any daemon threads created, regardless of number, are all stopped after the InProcessResolver is complete.

**Review by chrfwow — APPROVED** [review]

**Review by aepfli — APPROVED** [review]

**Review by toddbaert — APPROVED** [review]
