### PR TITLE
fix: issue on unknown field

### LINKED ISSUE #582: (bug) The latest version of java OpenFeature provider doesn't support relay proxy version v1.3.0+
### Observed behavior

dev.openfeature.contrib.providers.gofeatureflag.GoFeatureFlagProvider fails to parse "cacheable" attribute of relay proxy response. This flag is added in v1.3.0 into VariationResult structure.
Used SDK and providers versions:
 'dev.openfeature:sdk:1.3.0'
 'dev.openfeature.contrib.providers:go-feature-flag:0.2.3'

### Expected Behavior

New providers version that is able to parse the latest relay proxy response is available.

### Steps to reproduce

_No response_

### PR DESCRIPTION
**Pull request by thomaspoignant**
## This PR
Version `1.4.0` of the GO Feature Flag relay proxy is adding a new field in the JSON response and this was breaking the provider.

This PR provides a fix to ignore if unknown fields are present in the JSON response.

### Related Issues
Fixes: https://github.com/thomaspoignant/go-feature-flag/issues/582

### CODE REVIEW

File: providers/go-feature-flag/src/main/java/dev/openfeature/contrib/providers/gofeatureflag/GoFeatureFlagProvider.java [hunk 1]
```diff
@@ -197,7 +200,10 @@ private <T> ProviderEvaluation<T> resolveEvaluationGoFeatureFlagProxy(
                 if (Reason.DISABLED.name().equalsIgnoreCase(goffResp.getReason())) {
                     // we don't set a variant since we are using the default value, and we are not able to know
                     // which variant it is.
-                    return ProviderEvaluation.<T>builder().value(defaultValue).reason(Reason.DISABLED.name()).build();
+                    return ProviderEvaluation.<T>builder()
+                            .value(defaultValue)
+                            .variant(goffResp.getVariationType())
```
Comment (toddbaert) [inline providers/go-feature-flag/src/main/java/dev/openfeature/contrib/providers/gofeatureflag/GoFeatureFlagProvider.java:205]: Is `VariationType` a new addition to GoFF?

File: providers/go-feature-flag/src/main/java/dev/openfeature/contrib/providers/gofeatureflag/GoFeatureFlagProvider.java [hunk 2]
```diff
@@ -44,7 +46,8 @@
 public class GoFeatureFlagProvider implements FeatureProvider {
     private static final String NAME = "GO Feature Flag Provider";
     private static final ObjectMapper requestMapper = new ObjectMapper();
-    private static final ObjectMapper responseMapper = new ObjectMapper();
+    private static final ObjectMapper responseMapper = new ObjectMapper()
+            .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
```
Comment (toddbaert) [inline providers/go-feature-flag/src/main/java/dev/openfeature/contrib/providers/gofeatureflag/GoFeatureFlagProvider.java:50]: I've been bit by this before :(

**Review by toddbaert — APPROVED** [review]

File: providers/go-feature-flag/src/main/java/dev/openfeature/contrib/providers/gofeatureflag/GoFeatureFlagProvider.java (hunk 2 above)
Comment (thomaspoignant) [reply providers/go-feature-flag/src/main/java/dev/openfeature/contrib/providers/gofeatureflag/GoFeatureFlagProvider.java:50]: me too 😭 I don't know why I have not configure it correctly this time.
